import {
  LayoutDashboard,
  CalendarClock,
  ArrowLeftRight,
  CreditCard,
  History,
  Tags,
  FileBarChart2,
  BadgeDollarSign,
  Download,
  TriangleAlert,
  ArrowLeftToLine,
  ArrowRightFromLine,
  Wallet,
  Landmark,
  Copy,
  Check,
} from 'lucide-angular';

export const Icons = {
  LayoutDashboard,
  CalendarClock,
  ArrowLeftRight,
  CreditCard,
  History,
  Tags,
  FileBarChart2,
  BadgeDollarSign,
  Download,
  TriangleAlert,
  ArrowLeftToLine,
  ArrowRightFromLine,
  Wallet,
  Landmark,
  Copy,
  Check,
} as const;
